variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://192.168.1.9:2375
  DOCKER_TLS_CERTDIR: ""

image: mcr.microsoft.com/dotnet/core/aspnet:3.1
stages:
- checkout
checkout:
  stage: checkout
  artifacts: 
    paths:
      - source
    expire_in: 10m
  script:
  - git clone https://github.com/pforsthoff/testninja.git source
  - docker build -f Dockerfile.orig -t pforsthoff/testninja . 