---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
  name: testninja-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testninja
  template:
    metadata:
      labels:
        app: testninja
    spec:
      containers:
      - name: testninja
        image: pforsthoff/testninja:latest
        ports:
        - containerPort: 80