apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2 
kind: Deployment 
metadata: 
  name: testninja-deployment 
spec: 
  selector: 
    matchLabels: 
      app: testninja 
  replicas: 1 # tells deployment to run 2 pods matching the template 
  template: 
    metadata: 
      labels: 
        app: testninja 
    spec: 
      containers: 
      - name: testninja 
        image: pforsthoff/testninja:latest 
        ports: 
        - containerPort: 80 
--- 
# https://kubernetes.io/docs/concepts/services-networking/service/#defining-a-service  
kind: Service 
apiVersion: v1 
metadata: 
  name: testninja-service 
spec: 
  selector: 
    app: testninja 
  ports: 
  - protocol: TCP 
    port: 80 
    targetPort: 80 
    nodePort: 31000 
  type: NodePort 