kind: Pod
apiVersion: v1
metadata:
  name: testninja-app
  labels:
    app: testninja-app
spec:
  containers:
    - name: testninja-app
      image: pforsthoff/testninja
  serviceAccount: jenkins
---

kind: Service
apiVersion: v1
metadata:
  name: testninja-service
spec:
  selector:
    app: testninja-app
  ports:
    - name: http
      port: 80
      targetPort: 80 # Default port for image
