kind: Pod
apiVersion: v1
metadata:
  name: testninja-app
  namespace: jenkins
  labels:
    app: testninja-app
spec:
  containers:
    - name: testninja-app
      image: pforsthoff/testninja
      
  serviceAccount: jenkins
---

kind: Service
apiVersion: v1
metadata:
  name: testninja-service
  namespace: jenkins
spec:
  selector:
    app: testninja-app
  ports:
    - name: http
      port: 80
      targetPort: 80 # Default port for image
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: testninja
  namespace: jenkins
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: testninja.csharpsnippets.local
    http:
      paths:
      - path: /
        backend:
          serviceName: testninja-service
          servicePort: http